### ISSUE TITLE
Populate Repository

### ISSUE THREAD

**Issue by 05dirnbe** [05dirnbe/nefi#1]
Please go ahead and transfer the contents of your repos to here. Don't forget to structure the branches like we discusses. Make sure you dont push unused stuff.

Good luck!

**Comment by Rapdrei** [comment]
I pushed the source code to master and created a branch py_deploys. Currently we have the win_build as well as the osx_build in py_deploys. Phillipp will push the pydeploy source code later.
I also created a branch gh_pages in case you want us to create a git hub page. If not we will just link the mpi page for nefi in the repository.

**Comment by Rapdrei** [comment]
Do you want us to create a git wiki additionally to our documentation and the webpage provided by the mpi?

**Comment by 05dirnbe** [comment]
I think that a git wiki is not necessary at this point. But let us discuss this issue in our next meeting.
