### ISSUE TITLE
Clean up my mistakes

### ISSUE THREAD

**Issue by 05dirnbe** [05dirnbe/nefi#10]
Ahem, yeah, it seems that after my commit (instructed by you) of the nefi webpage the repo is messed up. Please put all the webpage related things in a folder and restructure accordingly.

**Comment by Rapdrei** [comment]
Hi Michael, your changes had no effect on the repository. :+1: 
You were able to push the website on a separate branch? if not you can also send me the content or put it into a google drive folder. I will create the website branch for you and make the initial commit.
