### ISSUE TITLE
Complete "About Software" text

### ISSUE THREAD

**Issue by LumPenPacK** [05dirnbe/nefi#18]
For the release we should complete this section.
As we discussed in the last meeting we might need to add different types of contributors in the credits. Not sure if we should even distinguish between the different parts such as UI, Algorithm, Model etc.

**Authors of NEFI 2.0 software**: 

- Andreas Firczynski
- Dennis Groß
- Martino Bruni
- Michael Dirnberger
- Pavel Shkadzko
- Philipp Reichert
- Sebastian Schattner

**Authors of NEFI 1.0 software**: 

- Michael Dirnberger
- Tim Kehl
- Adrian Neumann,

**Other contributors** :
     
**Algorithm references** : 

**Web page** : 
- http://nefi.mpi-inf.mpg.de/

**Version** : 
- 2.0.0

**Comment by 05dirnbe** [comment]
In principle this is ok. I think we can lose the algorithm references as well as other contributors. we should, however, add a note inviting people to contribute and link to the repo.

Id use developers instead of authors. Please add the link to the original paper on sci.rep.

**Comment by LumPenPacK** [comment]
Added with 9c382da
