### ISSUE TITLE
Pipeline calculates all steps again even though only one step has changed

### ISSUE THREAD

**Issue by LumPenPacK** [05dirnbe/nefi#29]
There seems to be a bug where the pipeline calculates all steps again even if it's not necessary. We need to take look into this.

**Comment by tastyminerals** [comment]
When does this happen? Any more info?

**Comment by LumPenPacK** [comment]
Example: Load Junius pipeline -> Run the pipeline -> Swap the last two step -> Run the pipeline again -> NEFI calculates the whole pipeline again although it's only necessary to calculate the last two steps again.

**Comment by tastyminerals** [comment]
That is because `move_category()` function does not call `alg.set_modified()` for the swapped categories.
