### ISSUE TITLE
thinning.py conflicts with thinning module

### ISSUE THREAD

**Issue by tastyminerals** [05dirnbe/nefi#35]
Updated to the latest version and ran a pipeline on a sample image.
```
Failed to process pipeline
Traceback (most recent call last):
  File "/home/tastyminerals/dev/nefi_rem/nefi/nefi2/view/main_controller.py", line 1883, in run
    self.pipeline.process()
  File "/home/tastyminerals/dev/nefi_rem/nefi/nefi2/model/pipeline.py", line 297, in process
    cat.process(data)
  File "/home/tastyminerals/dev/nefi_rem/nefi/nefi2/model/categories/_category.py", line 136, in process
    selected_alg.process(args)
  File "nefi2/model/algorithms/thinning.py", line 50, in process
    skeleton = thinning.guo_hall_thinning(args[0].copy())
AttributeError: module 'thinning' has no attribute 'guo_hall_thinning'
Current cat <segmentation.CatBody object at 0x7fbbda5fd6a0>
 ```

**Comment by LumPenPacK** [comment]
Does it always happen to you? I couldn't reproduce this error.

**Comment by tastyminerals** [comment]
It happens with any image.

**Comment by LumPenPacK** [comment]
It doesn't break anything on my machine. Neither on Windows nor on Linux but I can rename this algorithm anyway.

**Comment by tastyminerals** [comment]
Are you sure you have the latest version from git?
Well this is what exactly happening on my machine, **thinning** module is shadowed by instantiated `thinning.py` which does not have `guo_hall_thinning` function.

**Comment by LumPenPacK** [comment]
Yes, I'm using the latest commit from master branch and everything is working for me. So, renaming thinning.py into something different solves the problem for you? In order to prevent other people run into this problem we should just rename it.
