### ISSUE TITLE
thinning module can not be found

### ISSUE THREAD

**Issue by tastyminerals** [05dirnbe/nefi#43]
I am trying to install **nefi** from source and cannot find **thinning** module.
Where can I find it?

**Comment by buhl22** [comment]
https://pypi.python.org/pypi?name=thinning_py3&version=1.2.3&:action=display
I think for me even pip3 install thinning_py3 worked.
here is the installation guide: http://nefi.mpi-inf.mpg.de/documentation/rst_files/Installation.html

**Comment by tastyminerals** [comment]
Ah, yeah, I completely forgot.Thanks.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: buhl22Sent: Monday, May 30, 2016 09:59To: 05dirnbe/nefiReply To: 05dirnbe/nefiCc: tastyminerals; AuthorSubject: Re: [05dirnbe/nefi] thinning module can not be found (#43)https://pypi.python.org/pypi?name=thinning_py3&version=1.2.3&:action=display
I think for me even pip3 install thinning_py3 worked.
here is the installation guide: http://nefi.mpi-inf.mpg.de/documentation/rst_files/Installation.html

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
