### ISSUE TITLE
Python example for the basic steps required to perform graph analysis

### ISSUE THREAD

**Issue by raplima** [05dirnbe/nefi#47]
I've seen on the paper you published the following:
"...we provide a minimal Python program that illustrates the basic steps required to perform graph analysis. It shows how to read NEFI’s output from disk and how to compute a histogram of a given edge attribute. The code can be downloaded from NEFI’s project page at the Max Planck Institute for Informatics, http://nefi.mpi-inf.mpg.de, (2015)."

After some searching here on github and in the NEFI webpage, I could not find such program. Could you point me in the right direction?
My main issue is that I couldn't find out what is the correct format for reading the Graph...txt output from NEFI (read_adjlist, read_edgelist...). I intend to read the output graph and plot it with correct positioning based on pixel locations (as NEFI does in the GUI).

Thank you.

**Comment by tastyminerals** [comment]
Have you tried: https://github.com/05dirnbe/nefi/archive/windows_64bit_build.zip

**Comment by raplima** [comment]
Network output from NEFI is multiline_adjlist, to read an exported file:

graph_in = nx.read_multiline_adjlist("graph_nefi_out.txt",delimiter='|')
