### ISSUE TITLE
Make graph line thickness relative to the width of the according graph edge

### ISSUE THREAD

**Issue by Rapdrei** [05dirnbe/nefi#9]
Currently we have our graph lines thickness fixed by a number. Instead, we want the graph lines to have the thickness according to the underlying line width in the image. Every edge will have its own width.

**Comment by Rapdrei** [comment]
Is it desirable to let the user decide which color the lines and the graph vertices will have? If so we could add this option in a menu item edit or view since those are changes a user wont do frequently.
Also we could add a slider which lets the user increase/decrease the vertices thickness.

**Comment by 05dirnbe** [comment]
Wait a sec. What does that even mean "relative to the overlapping graph lines"? What we really want is the following: NEFI measures the width of the structures it sees in the original input image. This is a number in pixel and stored as an edge attribute called "width". When it comes to drawing the edge, we want to grab this number to set the width of the drawing. When the graph is drawn onto of the original image, the edges coincide (in a perfect world).

**Comment by 05dirnbe** [comment]
When it comes to choosing the color, node size, etc, we need to ask ourselves whether we add value by doing so. If you ask me, the color does not matter. What matters is that the colors of the edges and the nodes are easily distinguishable for colorblind people. Similarly, i dont really care about the node size right now, but I can imagine that this could be a feature desirable in the future.

**Comment by Rapdrei** [comment]
Ok good that you told us. We will make it so.

**Comment by adrianN** [comment]
We also compute the variance. Maybe it's nice to also visualize this, perhaps via blurring?

**Comment by Rapdrei** [comment]
How exactly would you show the variance? If i understood correct we need to show the same amount of blur along the complete edge. Then the edge would still look uniform.

**Comment by adrianN** [comment]
If the standard deviation is x pixels and the width is y pixels, apply gaussian blur with radius x to the line of thickness y. Or something like that to give some visual indication of measurement error or whatever causes the variance.

**Comment by Rapdrei** [comment]
Ok, we will first implement it according to Michael's sprecification. Afterwards ill create another branch implementing it like you suggested. By checking out the two different branches you can then later compare what type of edge rendering is better (we could possibly add a menu option two switch between those).

**Comment by Rapdrei** [comment]
I changed the implementation to satisfy Michael's specification.

**Comment by Rapdrei** [comment]
> If the standard deviation is x pixels and the width is y pixels, apply gaussian blur with radius x to the line of thickness y. Or something like that to give some visual indication of measurement error or whatever causes the variance. Sharp edges have little variance, blurry edges don't have a reliable width.

Gaussian Blur always apllies to the whole image using a kernel size. So instead i simply interpolate the color transparency based on the edge's standard deviation:

``` python
def draw_edges(img, graph, col=(0, 0, 255)):
    """
    Draw network edges on the input image.

    Args:
        | *img* : Input image where edges are drawn
        | *graph* : Input graph containing the edges
    Kwargs:
        | *col* : colour for drawing

    Returns:
        Input image img with nodes drawn into it
    """
    edg_img = numpy.copy(img)
    for (x1, y1), (x2, y2) in graph.edges_iter():
        start = (y1, x1)
        end = (y2, x2)
        diam = graph[(x1, y1)][(x2, y2)]['width']
        # variance value computed during graph detection
        width_var = graph[(x1, y1)][(x2, y2)]['width_var']
        # compute edges standard deviation by applying sqrt(var(edge))
        standard_dev = numpy.sqrt(width_var)
        if diam == -1: diam = 2
        diam = int(round(diam))
        if diam > 255:
            print('Warning: edge diameter too large for display. Diameter has been reset.')
            diam = 255
        # access color triple
        (b, g, r) = col
        # set opacity based by standard deviation and some selected divider
        opacity = (standard_dev % 10) / 10
        # opacity must be in [0, 1]
        if opacity > 1.0:
            opacity = 1
        # set overlay in this case white
        overlay = (0, 0 ,0) 
        # compute target color based on the transparency formula
        target_col = (b == 0 if 0 else (opacity * 255 + (1 - opacity) * b),
                      (g == 0 if 0 else opacity * 255 + (1 - opacity) * g),
                      (r == 0 if 0 else opacity * 255 + (1 - opacity) * r))
        # draw the line
        cv2.line(edg_img, start, end, target_col, diam)

    edg_img = cv2.addWeighted(img, 0.5, edg_img, 0.5, 0)
    return edg_img
```
I use the transparency formula from [here](https://www.viget.com/articles/equating-color-and-transparency). Since the opacity is in [0, 1] we need to calculate the modulo of from the standard deviation and 10. Now we get a number x  in [0, 10]. Dividing x by 10 gives us the opacity value between [0, 1]. This algorithm works based on the assumption that the standard deviation of the edges are around the same value.

Another option would be to let the user specify its custom divider value to bring the standard deviation into [0, 1]. In this case: opacity := standard_dev / DIVIDER

I would like to make the "blurry edges" feature available for the user by clicking the a checkbox "blurry edges" in the view menu.

You can try it out by checking out the edge_blur branch.

**Comment by Rapdrei** [comment]
Note: i think we could make the calculation much more efficient by just using the variance instead of the standard deviation. We are just interested in the differences of the standard deviation's so the square from the variance shouldn't be much of a deal because of the modulo 10 / div 10.

**Comment by adrianN** [comment]
1. You could draw the edge on a bitmap, blur the bitmap and overlay in on the image.
2. I agree about the variance vs the standard dev. In any case, I wouldn't use numpy.sqrt where math.sqrt will work. Have you tried extracting all variances and applying numpy.sqrt to the array of variances? It's an array method after all. But allocating the array probably eats any performance to be gained there.
3. edges_iter can return the edge data. That saves some dictionary lookups.
4. there is inconsistent bracing in the target_col computation. You could also do some common subexpression elimination there.
5. how can diam be -1 and why not write `diam = max(diam,2)`

**Comment by tastyminerals** [comment]
(Just my 5 cents once again) Profile every file you want to optimize with [line profiler](https://github.com/rkern/line_profiler) to see what exactly eats up the cpu.

Here is a a quick howto:
1. ``sudo pip install line_profiler``
2. open the algorithm file and insert "@profile" above the function definition you want to test
3. ``kernprof -l script_to_profile.py``
4. process any big image
5. ``python3 -m line_profiler script_to_profile.py.lprof``
